set INCLUDE_DIRS=-Isrc -I<GLFW3 INCLUDE DIRECTORY> -I<GLEW INCLUDE DIRECTORY> -I<LODEPNG INCLUDE DIRECTORY>
set LIB_DIRS=-LC:\Libraries\GLFW3\lib-mingw
set FLAGS=USE_GLFW=3
set SRC_FILES=src\Main.cpp
set OUTPUT_NAME=webcpp.html

em++ %INCLUDE_DIRS% %LIB_DIRS% %SRC_FILES% <GLEW.C> <LODEPNG.CPP> -o web\%OUTPUT_NAME% -s %FLAGS%

pause